### PR TITLE
Rewrite of CSS and HTML as well as minor fixes.

### PR DESCRIPTION
**Pull request by ahstro**
This is, for the most part, a rewrite of the CSS and HTML.
There was a lot of the CSS that was very badly formatted or not even used (I literally cut over 1000 lines from brass-min.css after formatting it) so I've tidied it up a bit.
I moved all relevant parts of both brass-min.css and the external default.css into a single stylesheet called style.css.

Besides fixing the CSS, I also did a few style changes/bug fixes to the website, such as fixing the border of the tables and the width of the pic-Rounded class (I assumed that it wasn't supposed to look like that).

I've updated the F-Droid icon to the latest version.

I've added an APK download to Firefox (I wanted to, and if it's okay, plan to add more APK downloads, but I didn't want to add that many features to this pull request, I just wanted to fix the CSS).

### CODE REVIEW

**Comment by repat** [comment]
oh wow, thanks! I'm gonna go trough it step by step, probably takes a while. 

"I assumed that it wasn't supposed to look like that"
not sure what you mean but everyting was pretty much meant like it was. I'll have a look.

.apk is a good idea:)

neocities doesn't allow folders, so I have to revert that, sry

**Comment by repat** [comment]
Ok, I oversaw the "temporary". Anyway, I'm still including all of your stuff. Do you have twitter and jabber where we could talk? find mine at repat.de/about

**Comment by ahstro** [comment]
Thanks! I just added your Jabber account.

**Comment by repat** [comment]
It couldn't be merged automatically so I did it manually. Added you on Jabber but my Pidgin crashed, you might have to authorize me again.

**Pull request closed without merging**
