### PR TITLE
Added Kontalk

### PR DESCRIPTION
**Pull request by TheLastProject**
I've added Kontalk to this. The icon was taken from the F-droid store page.

I figured that putting it first in the list of alternatives made most sense, as the first proprietary application listed was WhatsApp.

Sorry for some of the spacing, I tried to copy the spacing I saw used, but everything seems to be different. This project kinda needs some cleaning up, if I dare say it.

But well, I hope this is useful to you.

### CODE REVIEW

**Comment by repat** [comment]
Sorry for the delay, I don't have a lot of time at the moment. You're right, I should really do something about the formatting, it got out of hand ;-) Didn't expect that much interest.

I've heard of Kontalk, somebody already suggested it. The reason why we didn't include it yet is, that droid-break wants to list only well tested and high quality apps. As far as I understood and telling from the download numbers at the Play Store, Kontalk is not quite there yet and still in some kind of beta phase. I know that this is a chicken/egg problem. I'm keeping an eye on them. I hope to include it rather soon, so I'll leave this request open for now.

**Comment by dalb8** [comment]
Kontalk is fairly stable; it's quite a simple app UI wise. It doesn't have all the features of say, Telegram but it's a decent replacement for SMS.
It is changing it's backend server to be more standard XMPP and that will correspond to version 3.0 of the client. For the end user of the current version, they shouldn't experience any problems.

**Comment by repat** [comment]
It's getting there apparently. Things like this are a sign of immature software though:

> *\* NOTE: encryption in this version is weak. If you want strong encryption wait for version 3.0 **

So I'd rather wait.

**Comment by daniele-athome** [comment]
I, for one, tell you to wait :-) thanks to @dalb8 for promoting.

**Comment by daniele-athome** [comment]
I'd like to announce that Kontalk 3.0 (XMPP) has entered the beta test phase. It's available for download from F-Droid and from Google Play beta channel.

**Comment by repat** [comment]
Thanks for the hint, I'm gonna try to keep track:)

**Pull request closed without merging**
