### PR TITLE
Added two PDF readers; MuPDF and VuDroid.

### PR DESCRIPTION
**Pull request by ahstro**

### CODE REVIEW

**Comment by ahstro** [comment]
Sorry about the indention ones. You were the one who mentioned indenting everything properly. I hope you trust me enough to not have to read through all of that, because wow, that'd be a bitch.

**Comment by repat** [comment]
I wait until everything's done, as discussed via email:)

**Comment by ahstro** [comment]
In that case you'll have to wait for a while. I just pushed QR Codes v0.1 to my qrcodes branch; you could clone it to see if you like it, it should have working QR codes (safety checking them now) but the popup box isn't very beautiful, there's barely any information, and it looks bad with long app names. [This is how the working ones look.](http://i.imgur.com/Kw49nC2.png) The broken ones have names split in half and/or some text outside the white backgorund. I'll fix it when I've slept; I'm sure I'll wonder what the fuck I was doing, looking back at my code tomorrow.

**Comment by repat** [comment]
Well good night then :P Thanks a lot!

**Comment by repat** [comment]
changed merged with other branch

**Pull request closed without merging**
